<Project>
  <Import Project="$(MSBuildThisFileDirectory)build/Suite.Generated.props" />

  <PropertyGroup>
    <LangVersion>$(SuiteCSharpLanguageVersion)</LangVersion>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Version>$(SuiteVersion)</Version>
    <Authors>$(SuiteAuthors)</Authors>
  </PropertyGroup>
</Project>
