<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>HeimForgeExample.Client</RootNamespace>
    <AssemblyName>HeimForgeExample.Client</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../HeimForgeExample.Common/HeimForgeExample.Common.csproj" />
    <PackageReference Include="JotunnLib" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
