// <auto-generated />
namespace HeimForgeExample.Common;

public static class SuiteConstants
{
    public const string Name = "HeimForgeExample";
    public const string Version = "0.1.0";
    public const string GuidRoot = "dev.heimforge.example";
}
