from __future__ import annotations

import json
import os
import subprocess
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


class ScaffoldTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.cfg = json.loads((ROOT / "suite.config.json").read_text(encoding="utf-8"))

    def test_metadata_is_structurally_synchronized(self):
        result = subprocess.run(
            ["python3", "scripts/suite_metadata.py", "check", "--structural-only"],
            cwd=ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        self.assertEqual(0, result.returncode, result.stdout)

    def test_all_configured_projects_exist_and_solution_mentions_them(self):
        sln = (ROOT / f"{self.cfg['rootNamespace']}.sln").read_text(encoding="utf-8")
        for project in self.cfg["projects"]:
            csproj = ROOT / "src" / project / f"{project}.csproj"
            self.assertTrue(csproj.is_file(), project)
            self.assertIn(f"src\\{project}\\{project}.csproj", sln)

    def test_deployment_classification_excludes_wrong_side(self):
        p = self.cfg["packages"]
        server = {p["commonModule"], *p["serverModules"]}
        client = {p["commonModule"], *p["requiredClientModules"], *p["optionalClientModules"], *p["clientOnlyModules"]}
        scopes = {name: item["scope"] for name, item in self.cfg["projects"].items()}
        self.assertFalse(any(scopes[m] == "clientOnly" for m in server))
        self.assertFalse(any(scopes[m] == "serverOnly" for m in client))
        server_only = {n for n, s in scopes.items() if s == "serverOnly"}
        client_only = {n for n, s in scopes.items() if s == "clientOnly"}
        self.assertTrue(server_only <= server)
        self.assertFalse(server_only & client)
        self.assertTrue(client_only <= client)
        self.assertFalse(client_only & server)

    def test_bash_scripts_parse_and_are_executable(self):
        for script in sorted((ROOT / "scripts").glob("*.sh")):
            self.assertTrue(os.access(script, os.X_OK), f"not executable: {script.name}")
            result = subprocess.run(
                ["bash", "-n", str(script)], text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT
            )
            self.assertEqual(0, result.returncode, f"{script.name}: {result.stdout}")

    def test_local_sensitive_configuration_is_ignored(self):
        gitignore = (ROOT / ".gitignore").read_text(encoding="utf-8")
        local_paths = ("Environment.props", ".valheim/dev.json")
        for required in (*local_paths, "artifacts/", "**/bin/", "**/obj/"):
            self.assertIn(required, gitignore)

        repository = subprocess.run(
            ["git", "rev-parse", "--is-inside-work-tree"],
            cwd=ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        if repository.returncode != 0:
            return
        for relative_path in local_paths:
            tracked = subprocess.run(
                ["git", "ls-files", "--error-unmatch", "--", relative_path],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
            )
            self.assertNotEqual(0, tracked.returncode, f"{relative_path} must not be tracked")

            ignored = subprocess.run(
                ["git", "check-ignore", "--quiet", "--", relative_path],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
            )
            self.assertEqual(0, ignored.returncode, f"{relative_path} must be ignored: {ignored.stdout}")

    def test_generated_constants_are_the_only_suite_constants_source(self):
        common_project = self.cfg["packages"]["commonModule"]
        generated = ROOT / "src" / common_project / "SuiteConstants.Generated.cs"
        self.assertTrue(generated.is_file())
        self.assertFalse((ROOT / "src" / common_project / "SuiteConstants.cs").exists())
        text = generated.read_text(encoding="utf-8")
        self.assertIn("<auto-generated", text)
        self.assertIn(self.cfg["pluginGuidRoot"], text)

    def test_net48_projects_use_cross_platform_reference_assemblies(self):
        for project, item in self.cfg["projects"].items():
            if item["targetFramework"] != "net48":
                continue
            text = (ROOT / "src" / project / f"{project}.csproj").read_text(encoding="utf-8")
            self.assertIn('PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies"', text)

    def test_runtime_debug_logging_contract(self):
        root_namespace = self.cfg["rootNamespace"]
        common = self.cfg["packages"]["commonModule"]
        common_dir = ROOT / "src" / common
        self.assertTrue((common_dir / "Diagnostics" / "RuntimeDiagnostics.cs").is_file())
        self.assertEqual(
            [],
            ET.parse(common_dir / f"{common}.csproj").findall(".//PackageReference"),
        )

        expected_packages = {"JotunnLib", "Microsoft.NETFramework.ReferenceAssemblies"}
        for suffix in ("ServerCore", "Client", "Shared.Diagnostics"):
            project = f"{root_namespace}.{suffix}"
            if project not in self.cfg["projects"]:
                continue
            plugin = (ROOT / "src" / project / "Plugin.cs").read_text(encoding="utf-8")
            self.assertRegex(
                plugin,
                r'Config\.Bind\(\s*"Development",\s*"DebugLogging",\s*false,',
            )
            self.assertIn(
                "new RuntimeDiagnostics(() => debugLogging.Value, Logger.LogInfo)",
                plugin,
            )
            project_file = ET.parse(ROOT / "src" / project / f"{project}.csproj")
            package_references = {
                item.attrib["Include"]
                for item in project_file.findall(".//PackageReference")
            }
            self.assertEqual(expected_packages, package_references)
            if suffix in ("ServerCore", "Client"):
                project_references = {
                    item.attrib["Include"]
                    for item in project_file.findall(".//ProjectReference")
                }
                self.assertFalse(
                    any("Shared.Diagnostics" in reference for reference in project_references)
                )

    def test_plugin_compatibility_boundaries_remain_as_designed(self):
        expectations = {
            "serverOnly": "CompatibilityLevel.NotEnforced, VersionStrictness.None",
            "clientOnly": "CompatibilityLevel.NotEnforced, VersionStrictness.None",
            "sharedOptional": "CompatibilityLevel.VersionCheckOnly, VersionStrictness.Minor",
        }
        for project, item in self.cfg["projects"].items():
            expected = expectations.get(item["scope"])
            if expected is None:
                continue
            plugin = (ROOT / "src" / project / "Plugin.cs").read_text(encoding="utf-8")
            self.assertIn(expected, plugin)

    def test_packaging_is_real_not_placeholder(self):
        text = (ROOT / "scripts/package.sh").read_text(encoding="utf-8")
        self.assertNotIn("Packaging scaffold only", text)
        self.assertTrue((ROOT / "scripts/package.py").is_file())

    def test_no_arbitrary_log_command_in_dev_schema(self):
        example = json.loads((ROOT / ".valheim/dev.json.example").read_text(encoding="utf-8"))
        self.assertNotIn("serverLogCommand", example)


if __name__ == "__main__":
    unittest.main()
